using System;
using System.Collections.Generic;
using System.Text;

namespace NestedObjects
{
    public class Student
    {
        /// <summary>
        /// The unique indentifier for students.
        /// This number is generated by the database.
        /// </summary>
        public int StudentID { get; set; }
        /// <summary>
        /// The student's first name.
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// The student's last name.
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// The student's date of birth.
        /// Time of the day is ignored.
        /// </summary>
        public DateTime? DateOfBirth { get; set; }
    }
}
